# Generated by Django 3.0.5 on 2020-05-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200502_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertiesTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=5000)),
            ],
        ),
    ]
